version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: roster
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password
      MYSQL_DATABASE: roster
      DJANGO_SETTINGS_MODULE: dataInCloud.settings

volumes:
  db-data:
