version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'roster'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
    command: ['--sql-mode=STRICT_TRANS_TABLES']
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: 'roster'
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: '12345'
      DJANGO_SETTINGS_MODULE: 'dataInCloud.settings'

volumes:
  db-data:
